#!/bin/bash

MINISHELL_PATH="../minishell"

# Check if the test file was specified
if [[ -z "$1" ]]; then
    echo "Usage: $0 <test_file>"
    exit 1
fi

TEST_FILE="$1"

BOLD="\e[1m"
YELLOW="\033[0;33m"
GREY="\033[38;5;244m"
PURPLE="\033[0;35m"
RED="\e[0;31m"
END="\033[0m"

chmod 000 ./test_files/invalid_permission
rm -rf ./outfiles/*
rm -rf ./bash_outfiles/*
rm -rf ./mini_outfiles/*
mkdir -p ./outfiles ./mini_outfiles ./bash_outfiles

printf $RED
echo "🔥🔥🔥 MiniShell Testing 🔥🔥🔥"
echo "----------------------------------"

PROMPT=$(echo -e "\nexit\n" | $MINISHELL_PATH | head -n 1 | sed "s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g")
REMOVE_COLORS="sed s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g"
REMOVE_EXIT="grep -v ^exit$"

printf $RED
echo "Running tests from $TEST_FILE"
echo "----------------------------------"

i=0
ok=0

while read teste; do
    ((i++))
    MINI_OUTPUT=$(echo -e "$teste" | $MINISHELL_PATH 2> /dev/null | $REMOVE_COLORS | grep -vF "$PROMPT" | $REMOVE_EXIT)
    MINI_OUTFILES=$(cp ./outfiles/* ./mini_outfiles &>/dev/null)
    MINI_EXIT_CODE=$(echo -e "$MINISHELL_PATH\n$teste\nexit\n" | bash &>/dev/null; echo $?)
    MINI_ERROR_MSG=$(trap "" PIPE && echo "$teste" | $MINISHELL_PATH 2>&1 > /dev/null | grep -o '[^:]*$')

    BASH_OUTPUT=$(echo -e "$teste" | bash 2> /dev/null)
    BASH_EXIT_CODE=$(echo $?)
    BASH_OUTFILES=$(cp ./outfiles/* ./bash_outfiles &>/dev/null)
    BASH_ERROR_MSG=$(trap "" PIPE && echo "$teste" | bash 2>&1 > /dev/null | grep -o '[^:]*$' | head -n1)

    OUTFILES_DIFF=$(diff ./bash_outfiles ./mini_outfiles)

    printf $YELLOW
    printf "Test %3s: " $i
    if [[ "$MINI_OUTPUT" == "$BASH_OUTPUT" && "$MINI_EXIT_CODE" == "$BASH_EXIT_CODE" && -z "$OUTFILES_DIFF" ]]; then
        printf ✅
        ((ok++))
        if [ "$MINI_ERROR_MSG" != "$BASH_ERROR_MSG" ]; then
            printf "⚠️ "
        fi
    else
        printf ❌
    fi
    printf "$GREY $teste \n$END"
    if [ "$OUTFILES_DIFF" ]; then
        # echo "$OUTFILES_DIFF"
        echo ===bash outfiles:===
        cat ./bash_outfiles/*
        echo ===mini outfiles:===
        cat ./mini_outfiles/*
    fi
    if [ "$MINI_OUTPUT" != "$BASH_OUTPUT" ]; then
        echo mini output = \($MINI_OUTPUT\)
        echo bash output = \($BASH_OUTPUT\)
    fi
    if [ "$MINI_EXIT_CODE" != "$BASH_EXIT_CODE" ]; then
        echo mini exit code = $MINI_EXIT_CODE
        echo bash exit code = $BASH_EXIT_CODE
    fi
    if [ "$MINI_ERROR_MSG" != "$BASH_ERROR_MSG" ]; then
        echo mini error = \($MINI_ERROR_MSG\)
        echo bash error = \($BASH_ERROR_MSG\)
    fi
done < $TEST_FILE

printf $PURPLE
printf $BOLD
echo   $ok/$i
printf $END

if [[ "$ok" == "$i" ]]; then
    echo "😎 All tests passed! 😎"
    exit 0
else
    echo "😭 Some tests failed! 😭"
    exit 1
fi
